/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaz;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;
import java.io.File;
import java.io.BufferedReader;
import java.io.FileReader;
import EDD.GrafoSinaptico;
import EDD.TablaHashNeurotransmisores;
import Entidades.Neurona;
import Entidades.Sinapsis;
import Logica.ControladorPrincipal;
import java.awt.BorderLayout;
import javax.swing.JOptionPane;
import org.graphstream.graph.Graph;
import org.graphstream.graph.Node;
import org.graphstream.graph.implementations.SingleGraph;
import org.graphstream.ui.view.Viewer;
import org.graphstream.ui.swingViewer.ViewPanel;
import java.io.PrintWriter;
/**
 *
 * @author gonzalo
 */
public class InterfazUsuario extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(InterfazUsuario.class.getName());

    /**
     * Creates new form Interfaz
     */
    public InterfazUsuario() {
    
        initComponents();
        PanelContenedor.removeAll();
        PanelContenedor.add(VistaInicio); 
        PanelContenedor.repaint();
        PanelContenedor.revalidate();
        
        this.setLocationRelativeTo(null); 
        this.setResizable(false); 
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Sidebar = new javax.swing.JPanel();
        CargaCSV = new javax.swing.JButton();
        Neuronas = new javax.swing.JButton();
        Sinapsis = new javax.swing.JButton();
        RedGrafo = new javax.swing.JButton();
        SimulacionDijkstra = new javax.swing.JButton();
        dfsybfs = new javax.swing.JButton();
        Neurotransmisor = new javax.swing.JButton();
        PanelContenedor = new javax.swing.JPanel();
        VistaCargaCSV = new javax.swing.JPanel();
        BotonDatosRed = new javax.swing.JButton();
        BotonDicNeuro = new javax.swing.JButton();
        SalidaCSVdicNeuro = new javax.swing.JScrollPane();
        AreaTextoNeuro = new javax.swing.JTextArea();
        SalidaCSVred = new javax.swing.JScrollPane();
        AreaTextoRed = new javax.swing.JTextArea();
        csvneuromod = new javax.swing.JButton();
        csvredmod = new javax.swing.JButton();
        VistaNeurona = new javax.swing.JPanel();
        NeuronaScroll = new javax.swing.JScrollPane();
        TextAreaNeurona = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        IdNeurona = new javax.swing.JTextField();
        EliminarNeurona = new javax.swing.JButton();
        AgregarNeurona = new javax.swing.JButton();
        VistaSinapsis = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        AgregarSinapsis = new javax.swing.JButton();
        EliminarSinapsis = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TextAreaSinapsis = new javax.swing.JTextArea();
        IdDestino = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        IdOrigen1 = new javax.swing.JTextField();
        CoeficienteK = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        Distancia = new javax.swing.JTextField();
        Neurotransmisor1 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        VistaNeurotransmisor = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        AgregarNeurotrans = new javax.swing.JButton();
        EliminarNeurotans = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        TextAreaNeurotrans = new javax.swing.JTextArea();
        nombreneurotrans = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        IdNeurotrans = new javax.swing.JTextField();
        descripcionneurotrans = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        efectoneurotrans = new javax.swing.JTextField();
        velocidadneurotrans = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        VistaVerRed = new javax.swing.JPanel();
        muestraGrafo = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        VistaDijkstra = new javax.swing.JPanel();
        grafodijkstra = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        IdNeuronaOrigen = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        IdNeuronaDestino = new javax.swing.JTextField();
        Dijkstra = new javax.swing.JButton();
        simulacionfatiga = new javax.swing.JButton();
        fatiga = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        resultDijkstra = new javax.swing.JTextArea();
        grafooriginal = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        VistaDFSyBFS = new javax.swing.JPanel();
        grafo = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        IdNeuronaFuente = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        resultDFSyBFS = new javax.swing.JTextArea();
        DFS = new javax.swing.JButton();
        BFS = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        VistaInicio = new javax.swing.JPanel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Sidebar.setBackground(new java.awt.Color(51, 51, 51));
        Sidebar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        CargaCSV.setText("Carga CSV");
        CargaCSV.addActionListener(this::CargaCSVActionPerformed);
        Sidebar.add(CargaCSV, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 39, 167, -1));

        Neuronas.setText("Edición Neurona");
        Neuronas.addActionListener(this::NeuronasActionPerformed);
        Sidebar.add(Neuronas, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 114, 167, -1));

        Sinapsis.setText("Edición Sinapsis");
        Sinapsis.addActionListener(this::SinapsisActionPerformed);
        Sidebar.add(Sinapsis, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 170, -1));

        RedGrafo.setText("Ver Red Neuronal");
        RedGrafo.addActionListener(this::RedGrafoActionPerformed);
        Sidebar.add(RedGrafo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, 167, -1));

        SimulacionDijkstra.setText("Simulación Dijkstra");
        SimulacionDijkstra.addActionListener(this::SimulacionDijkstraActionPerformed);
        Sidebar.add(SimulacionDijkstra, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, 167, -1));

        dfsybfs.setText("Simulación DFS y BFS");
        dfsybfs.addActionListener(this::dfsybfsActionPerformed);
        Sidebar.add(dfsybfs, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 420, 167, -1));

        Neurotransmisor.setText("Edición Neurotrans.");
        Neurotransmisor.addActionListener(this::NeurotransmisorActionPerformed);
        Sidebar.add(Neurotransmisor, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 170, -1));

        getContentPane().add(Sidebar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 210, 510));

        PanelContenedor.setLayout(new java.awt.CardLayout());

        VistaCargaCSV.setBackground(new java.awt.Color(245, 245, 245));
        VistaCargaCSV.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BotonDatosRed.setBackground(new java.awt.Color(245, 245, 245));
        BotonDatosRed.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        BotonDatosRed.setText("Cargar CSV red sináptica");
        BotonDatosRed.addActionListener(this::BotonDatosRedActionPerformed);
        VistaCargaCSV.add(BotonDatosRed, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, 340, -1));

        BotonDicNeuro.setBackground(new java.awt.Color(245, 245, 245));
        BotonDicNeuro.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        BotonDicNeuro.setText("Cargar CSV diccionario de neurotransmisores");
        BotonDicNeuro.addActionListener(this::BotonDicNeuroActionPerformed);
        VistaCargaCSV.add(BotonDicNeuro, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, 350, -1));

        AreaTextoNeuro.setEditable(false);
        AreaTextoNeuro.setColumns(20);
        AreaTextoNeuro.setRows(5);
        SalidaCSVdicNeuro.setViewportView(AreaTextoNeuro);

        VistaCargaCSV.add(SalidaCSVdicNeuro, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 310, 560, 170));

        AreaTextoRed.setEditable(false);
        AreaTextoRed.setColumns(20);
        AreaTextoRed.setRows(5);
        SalidaCSVred.setViewportView(AreaTextoRed);

        VistaCargaCSV.add(SalidaCSVred, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, 560, 170));

        csvneuromod.setText("Guardar CSV");
        csvneuromod.addActionListener(this::csvneuromodActionPerformed);
        VistaCargaCSV.add(csvneuromod, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 270, 200, -1));

        csvredmod.setText("Guardar CSV");
        csvredmod.addActionListener(this::csvredmodActionPerformed);
        VistaCargaCSV.add(csvredmod, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 40, 200, -1));

        PanelContenedor.add(VistaCargaCSV, "card7");

        VistaNeurona.setBackground(new java.awt.Color(245, 245, 245));
        VistaNeurona.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TextAreaNeurona.setColumns(20);
        TextAreaNeurona.setRows(5);
        NeuronaScroll.setViewportView(TextAreaNeurona);

        VistaNeurona.add(NeuronaScroll, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, 560, 280));

        jLabel4.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        jLabel4.setText("Insete el ID de la Neurona que desea Agregar o Eliminar:");
        VistaNeurona.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, -1, -1));

        IdNeurona.addActionListener(this::IdNeuronaActionPerformed);
        VistaNeurona.add(IdNeurona, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, 360, 40));

        EliminarNeurona.setText("Eliminar Neurona");
        EliminarNeurona.addActionListener(this::EliminarNeuronaActionPerformed);
        VistaNeurona.add(EliminarNeurona, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, 150, 40));

        AgregarNeurona.setText("Agregar Neurona");
        AgregarNeurona.addActionListener(this::AgregarNeuronaActionPerformed);
        VistaNeurona.add(AgregarNeurona, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 120, 150, 40));

        PanelContenedor.add(VistaNeurona, "card6");

        VistaSinapsis.setBackground(new java.awt.Color(245, 245, 245));
        VistaSinapsis.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        jLabel6.setText("ID Destino");
        VistaSinapsis.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, -1, -1));

        AgregarSinapsis.setText("Agregar Sinapsis");
        AgregarSinapsis.addActionListener(this::AgregarSinapsisActionPerformed);
        VistaSinapsis.add(AgregarSinapsis, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 220, 150, 40));

        EliminarSinapsis.setText("Eliminar Sinapsis");
        EliminarSinapsis.addActionListener(this::EliminarSinapsisActionPerformed);
        VistaSinapsis.add(EliminarSinapsis, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 220, 150, 40));

        TextAreaSinapsis.setColumns(20);
        TextAreaSinapsis.setRows(5);
        jScrollPane1.setViewportView(TextAreaSinapsis);

        VistaSinapsis.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, 580, 200));

        IdDestino.addActionListener(this::IdDestinoActionPerformed);
        VistaSinapsis.add(IdDestino, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 130, 160, 30));

        jLabel7.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        jLabel7.setText("Obligatorio para Agregar no para Eliminar:");
        VistaSinapsis.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 30, -1, -1));

        jLabel8.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        jLabel8.setText("ID Origen");
        VistaSinapsis.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, -1, -1));

        IdOrigen1.addActionListener(this::IdOrigen1ActionPerformed);
        VistaSinapsis.add(IdOrigen1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 90, 160, 30));

        CoeficienteK.addActionListener(this::CoeficienteKActionPerformed);
        VistaSinapsis.add(CoeficienteK, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 150, 160, 30));

        jLabel9.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        jLabel9.setText("Coef. K");
        VistaSinapsis.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 160, 60, -1));

        jLabel10.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        jLabel10.setText("Campos para Agregar o Eliminar Sinapsis:");
        VistaSinapsis.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, -1, -1));

        jLabel11.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        jLabel11.setText("Distancia");
        VistaSinapsis.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 80, -1, -1));

        Distancia.addActionListener(this::DistanciaActionPerformed);
        VistaSinapsis.add(Distancia, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 70, 160, 30));

        Neurotransmisor1.addActionListener(this::Neurotransmisor1ActionPerformed);
        VistaSinapsis.add(Neurotransmisor1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 110, 160, 30));

        jLabel12.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        jLabel12.setText("ID Neurotr.");
        VistaSinapsis.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 120, 80, -1));

        PanelContenedor.add(VistaSinapsis, "card3");

        VistaNeurotransmisor.setBackground(new java.awt.Color(245, 245, 245));
        VistaNeurotransmisor.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel21.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        jLabel21.setText("Nombre");
        VistaNeurotransmisor.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, -1, -1));

        AgregarNeurotrans.setText("Agregar Neurotransmisor");
        AgregarNeurotrans.addActionListener(this::AgregarNeurotransActionPerformed);
        VistaNeurotransmisor.add(AgregarNeurotrans, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 240, 310, 40));

        EliminarNeurotans.setText("Eliminar Neurotransmisor");
        EliminarNeurotans.addActionListener(this::EliminarNeurotansActionPerformed);
        VistaNeurotransmisor.add(EliminarNeurotans, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 60, 300, 40));

        TextAreaNeurotrans.setColumns(20);
        TextAreaNeurotrans.setRows(5);
        jScrollPane2.setViewportView(TextAreaNeurotrans);

        VistaNeurotransmisor.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, 580, 200));

        nombreneurotrans.addActionListener(this::nombreneurotransActionPerformed);
        VistaNeurotransmisor.add(nombreneurotrans, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 150, 160, 30));

        jLabel22.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        jLabel22.setText("Obligatorio para Agregar no para Eliminar");
        VistaNeurotransmisor.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, -1, -1));

        jLabel23.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        jLabel23.setText("ID");
        VistaNeurotransmisor.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, -1, -1));

        IdNeurotrans.addActionListener(this::IdNeurotransActionPerformed);
        VistaNeurotransmisor.add(IdNeurotrans, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 70, 160, 30));

        descripcionneurotrans.addActionListener(this::descripcionneurotransActionPerformed);
        VistaNeurotransmisor.add(descripcionneurotrans, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 190, 160, 30));

        jLabel24.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        jLabel24.setText("Descripción");
        VistaNeurotransmisor.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 200, 100, -1));

        jLabel25.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        jLabel25.setText("Campos para Agregar o Eliminar Neurotransmisor");
        VistaNeurotransmisor.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, -1, -1));

        jLabel29.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        jLabel29.setText("Efecto");
        VistaNeurotransmisor.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, -1, -1));

        efectoneurotrans.addActionListener(this::efectoneurotransActionPerformed);
        VistaNeurotransmisor.add(efectoneurotrans, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 190, 160, 30));

        velocidadneurotrans.addActionListener(this::velocidadneurotransActionPerformed);
        VistaNeurotransmisor.add(velocidadneurotrans, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 150, 160, 30));

        jLabel30.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        jLabel30.setText("Velocidad");
        VistaNeurotransmisor.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 160, 80, -1));

        PanelContenedor.add(VistaNeurotransmisor, "card3");

        VistaVerRed.setBackground(new java.awt.Color(245, 245, 245));
        VistaVerRed.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        VistaVerRed.add(muestraGrafo, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, 540, 390));

        jLabel5.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        jLabel5.setText("Grafo Sináptico Resultante");
        VistaVerRed.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 30, 340, 30));

        PanelContenedor.add(VistaVerRed, "card2");

        VistaDijkstra.setBackground(new java.awt.Color(245, 245, 245));
        VistaDijkstra.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        VistaDijkstra.add(grafodijkstra, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 50, 270, 270));

        jLabel13.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jLabel13.setText("Grafo camino resultante");
        VistaDijkstra.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 18, 170, 20));

        IdNeuronaOrigen.addActionListener(this::IdNeuronaOrigenActionPerformed);
        VistaDijkstra.add(IdNeuronaOrigen, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 350, 180, 20));

        jLabel14.setFont(new java.awt.Font("Helvetica Neue", 0, 12)); // NOI18N
        jLabel14.setText("ID Neurona de Origen");
        VistaDijkstra.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 330, -1, -1));

        IdNeuronaDestino.addActionListener(this::IdNeuronaDestinoActionPerformed);
        VistaDijkstra.add(IdNeuronaDestino, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 400, 180, 20));

        Dijkstra.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        Dijkstra.setText("Ejecutar Simulación Dijkstra");
        Dijkstra.addActionListener(this::DijkstraActionPerformed);
        VistaDijkstra.add(Dijkstra, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 330, 230, 50));

        simulacionfatiga.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        simulacionfatiga.setText("Simular Fatiga");
        simulacionfatiga.addActionListener(this::simulacionfatigaActionPerformed);
        VistaDijkstra.add(simulacionfatiga, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 440, 130, 50));

        fatiga.setEditable(false);
        fatiga.setText("0");
        VistaDijkstra.add(fatiga, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 460, 100, -1));

        jLabel15.setText("Factor de Fatiga");
        VistaDijkstra.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 440, -1, 20));

        resultDijkstra.setColumns(20);
        resultDijkstra.setRows(5);
        jScrollPane3.setViewportView(resultDijkstra);

        VistaDijkstra.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 390, 260, -1));
        VistaDijkstra.add(grafooriginal, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 290, 270));

        jLabel16.setFont(new java.awt.Font("Helvetica Neue", 0, 12)); // NOI18N
        jLabel16.setText("ID Neurona de Destino");
        VistaDijkstra.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 380, -1, -1));

        jLabel17.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jLabel17.setText("Grafo Original");
        VistaDijkstra.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 20, 160, -1));

        PanelContenedor.add(VistaDijkstra, "card4");

        VistaDFSyBFS.setBackground(new java.awt.Color(245, 245, 245));
        VistaDFSyBFS.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        VistaDFSyBFS.add(grafo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 580, 250));

        jLabel18.setFont(new java.awt.Font("Helvetica Neue", 0, 12)); // NOI18N
        jLabel18.setText("Resultado del recorrido");
        VistaDFSyBFS.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 320, -1, -1));

        IdNeuronaFuente.addActionListener(this::IdNeuronaFuenteActionPerformed);
        VistaDFSyBFS.add(IdNeuronaFuente, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 350, 180, 20));

        resultDFSyBFS.setColumns(20);
        resultDFSyBFS.setRows(5);
        jScrollPane4.setViewportView(resultDFSyBFS);

        VistaDFSyBFS.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 340, 280, 140));

        DFS.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        DFS.setText("Ejecutra Recorrido DFS");
        DFS.addActionListener(this::DFSActionPerformed);
        VistaDFSyBFS.add(DFS, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 380, 230, 40));

        BFS.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        BFS.setText("Ejecutra Recorrido BFS");
        BFS.addActionListener(this::BFSActionPerformed);
        VistaDFSyBFS.add(BFS, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 430, 230, 40));

        jLabel19.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jLabel19.setText("Grafo evaluado (Verde Recorrido - Rojo Aislado)");
        VistaDFSyBFS.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 20, 370, -1));

        jLabel20.setFont(new java.awt.Font("Helvetica Neue", 0, 12)); // NOI18N
        jLabel20.setText("ID Neurona Fuente");
        VistaDFSyBFS.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 330, -1, -1));

        PanelContenedor.add(VistaDFSyBFS, "card5");

        VistaInicio.setBackground(new java.awt.Color(245, 245, 245));
        VistaInicio.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel26.setBackground(new java.awt.Color(0, 0, 0));
        jLabel26.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 1, 30)); // NOI18N
        jLabel26.setText("Bienvenido al SynapseLogic ");
        VistaInicio.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 40, 440, 60));

        jLabel27.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(51, 51, 51));
        jLabel27.setText("Grupo 1H");
        VistaInicio.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 340, -1, -1));

        jLabel28.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(51, 51, 51));
        jLabel28.setText("Presiona el botón de la acción que deseas realizar");
        VistaInicio.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 110, -1, -1));

        jLabel1.setText("Gonzalo Maza CI 32.710.984");
        VistaInicio.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 380, -1, -1));

        jLabel2.setText("Santiago Hernàndez CI 31.539.266");
        VistaInicio.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 440, -1, -1));

        jLabel3.setText("Andrés Benezra CI 30.715.072");
        VistaInicio.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 410, -1, -1));

        PanelContenedor.add(VistaInicio, "card8");

        getContentPane().add(PanelContenedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 0, 640, 510));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CargaCSVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CargaCSVActionPerformed
        PanelContenedor.removeAll();
        PanelContenedor.add(VistaCargaCSV);
        PanelContenedor.repaint();
        PanelContenedor.revalidate();    
    }//GEN-LAST:event_CargaCSVActionPerformed

    private void NeuronasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NeuronasActionPerformed
        PanelContenedor.removeAll();
        PanelContenedor.add(VistaNeurona);
        PanelContenedor.repaint();
        PanelContenedor.revalidate(); 
        
        ControladorPrincipal controlador = new ControladorPrincipal();
        GrafoSinaptico grafoGlobal = ControladorPrincipal.getGrafo();
        
        if (grafoGlobal != null) {
            TextAreaNeurona.setText(controlador.mostrarListaNeuronas());
        }   
      }//GEN-LAST:event_NeuronasActionPerformed

    private void SimulacionDijkstraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SimulacionDijkstraActionPerformed
        PanelContenedor.removeAll();
        PanelContenedor.add(VistaDijkstra);
        PanelContenedor.repaint();
        PanelContenedor.revalidate();
        
        GrafoSinaptico grafoGlobal = ControladorPrincipal.getGrafo();

        if (grafoGlobal == null || grafoGlobal.isEmpty() == true) {
            JOptionPane.showMessageDialog(this, "La red neuronal está vacía. Cargue datos antes de simular.", "Aviso", JOptionPane.WARNING_MESSAGE);
            return;
        }

        System.setProperty("org.graphstream.ui.renderer", "org.graphstream.ui.j2dviewer.J2DGraphRenderer");
        Graph graphOriginal = new SingleGraph("GrafoOriginal");
        graphOriginal.setStrict(false);
        graphOriginal.setAutoCreate(true);

        Neurona neuronaActual = grafoGlobal.getNeuronaInicio();
        while (neuronaActual != null) {
            String idString = neuronaActual.getId();
            Node n = graphOriginal.addNode(idString);
            n.setAttribute("ui.label", idString); 
            neuronaActual = neuronaActual.getSiguiente();
        }

        neuronaActual = grafoGlobal.getNeuronaInicio();
        while (neuronaActual != null) {
            Sinapsis sinapsisActual = neuronaActual.getConexiones().getPrimeraSinapsis();
            while (sinapsisActual != null) {
                String idOrigen = neuronaActual.getId();
                String idDestino = sinapsisActual.getDestino().getId();
                String idArista = idOrigen + "-" + idDestino;
                graphOriginal.addEdge(idArista, idOrigen, idDestino, true);
                sinapsisActual = sinapsisActual.getSiguiente();
            }
            neuronaActual = neuronaActual.getSiguiente();
        }
        
        graphOriginal.setAttribute("ui.stylesheet", "node { fill-color: green; size: 25px; text-size: 18px; text-style: bold; text-alignment: center; } edge { fill-color: black; }");

        Viewer viewerOrig = new Viewer(graphOriginal, Viewer.ThreadingModel.GRAPH_IN_ANOTHER_THREAD);
        viewerOrig.enableAutoLayout(); 
        ViewPanel viewPanelOrig = viewerOrig.addDefaultView(false); 

        grafooriginal.removeAll();
        grafooriginal.setLayout(new BorderLayout());
        grafooriginal.add(viewPanelOrig, BorderLayout.CENTER);
        grafooriginal.repaint();
        grafooriginal.revalidate();
    }//GEN-LAST:event_SimulacionDijkstraActionPerformed

    private void BotonDatosRedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonDatosRedActionPerformed
       

        
        boolean redCargadaEnMemoria = ControladorPrincipal.getRedCargadaEnMemoria();

        if (redCargadaEnMemoria) {
            JOptionPane.showMessageDialog(this, 
                "Alerta: Ya hay una red  cargada en memoria.\nRecuerda guardar tus datos actuales si hiciste modificaciones.", 
                "Advertencia de Sobreescritura", 
                JOptionPane.WARNING_MESSAGE);
        }

        JFileChooser fileChooser = new JFileChooser();
        FileNameExtensionFilter filter = new FileNameExtensionFilter(".CSV","csv");
        fileChooser.setFileSelectionMode(JFileChooser.FILES_ONLY);
        fileChooser.setFileFilter(filter);
        fileChooser.setDialogTitle("Seleccione el archivo CSV de la Red Neuronal");
        
        int seleccion = fileChooser.showOpenDialog(this);
        
        if (seleccion == JFileChooser.APPROVE_OPTION) {

            File archivo = fileChooser.getSelectedFile();
            String ruta = archivo.getAbsolutePath(); 
            
            try {
                BufferedReader lector = new BufferedReader(new FileReader(archivo));
                String linea;
                
                
                Logica.LectorCSV lectorLogico = new Logica.LectorCSV();
                if (redCargadaEnMemoria == true) {
                    ControladorPrincipal.vaciarGrafo(); 
                }
                Boolean aprobado = lectorLogico.leerRedNeuronal(ruta);
               
                if (aprobado == true) {
                    String contenidoCompleto = ""; 
                    
                    while ((linea = lector.readLine()) != null) {
                        contenidoCompleto += linea + "\n";
                    }
                    lector.close();
                    
                    AreaTextoRed.setText(contenidoCompleto);

                
                    ControladorPrincipal.setRedCargadaEnMemoria(true);
                }
                
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, "Error al leer el archivo: " + ex.getMessage());
            }
        }
    }//GEN-LAST:event_BotonDatosRedActionPerformed

    private void BotonDicNeuroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonDicNeuroActionPerformed
        

        boolean diccionario = ControladorPrincipal.getDiccionarioCargadoEnMemoria();


        if (diccionario == true) {
            JOptionPane.showMessageDialog(this, 
                "Alerta: Ya hay un diccionario de neurotransmisores cargado en memoria.\nRecuerda guardar tus datos actuales si hiciste modificaciones.", 
                "Advertencia de Sobreescritura", 
                JOptionPane.WARNING_MESSAGE);
        }

        JFileChooser fileChooser = new JFileChooser();
        FileNameExtensionFilter filter = new FileNameExtensionFilter(".CSV","csv");
        fileChooser.setFileSelectionMode(JFileChooser.FILES_ONLY);
        fileChooser.setFileFilter(filter);
        fileChooser.setDialogTitle("Seleccione el archivo CSV del Diccionario de Neurotransmisores");
        
        int seleccion = fileChooser.showOpenDialog(this);
        
        if (seleccion == JFileChooser.APPROVE_OPTION) {

            File archivo = fileChooser.getSelectedFile();
            String ruta = archivo.getAbsolutePath(); 
            
            try {
                BufferedReader lector = new BufferedReader(new FileReader(archivo));
                String linea;
                
                
                Logica.LectorCSV lectorLogico = new Logica.LectorCSV();
            
                if (diccionario == true) {
                    ControladorPrincipal.vaciarDiccionario(); 
                }
        
                Boolean aprobado = lectorLogico.leerDiccionarioHash(ruta);
                
                if (aprobado == true) {
                    String contenidoCompleto = ""; 
                    
                    while ((linea = lector.readLine()) != null) {
                        contenidoCompleto += linea + "\n";
                    }
                    lector.close();
                    
                    AreaTextoNeuro.setText(contenidoCompleto);
                    
                    ControladorPrincipal.setDiccionarioCargadoEnMemoria(true);
                }
                
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, "Error al leer el archivo: " + ex.getMessage());
            }
        }
    }//GEN-LAST:event_BotonDicNeuroActionPerformed

    private void RedGrafoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RedGrafoActionPerformed
        
        GrafoSinaptico grafoGlobal = ControladorPrincipal.getGrafo();

        if (grafoGlobal.isEmpty()) {
            JOptionPane.showMessageDialog(this, "La red neuronal está vacía. Cargue el CSV primero.", "Aviso", JOptionPane.WARNING_MESSAGE);
            return;
        }

        System.setProperty("org.graphstream.ui.renderer", "org.graphstream.ui.j2dviewer.J2DGraphRenderer");
        Graph graph = new SingleGraph("Cerebro");
        graph.setStrict(false);
        graph.setAutoCreate(true);

        Neurona neuronaActual = grafoGlobal.getNeuronaInicio();
        while (neuronaActual != null) {
            if (neuronaActual.getActivo()) {
                Node n = graph.addNode(neuronaActual.getId());
                n.setAttribute("ui.label", neuronaActual.getId()); 
            }
            neuronaActual = neuronaActual.getSiguiente();
        }

        neuronaActual = grafoGlobal.getNeuronaInicio();
        while (neuronaActual != null) {
                Sinapsis sinapsisActual = neuronaActual.getConexiones().getPrimeraSinapsis();
                
                while (sinapsisActual != null) {
                    if (sinapsisActual.getDestino().getActivo()) {
                        String idOrigen = neuronaActual.getId();
                        String idDestino = sinapsisActual.getDestino().getId();
                        String idArista = idOrigen + "-" + idDestino;

                        graph.addEdge(idArista, idOrigen, idDestino, true);
                    }
                    sinapsisActual = sinapsisActual.getSiguiente();
                }
            
            neuronaActual = neuronaActual.getSiguiente();
        }
        
            String styleSheet = "node {" +
                            "   fill-color: green;" +
                            "   size: 30px;" +
                            "   text-size: 24px;" +         
                            "   text-style: bold;" +        
                            "   text-alignment: center;" +
                            "}" +
                            "edge {" +
                            "   fill-color: black;" +
                            "}";
        graph.setAttribute("ui.stylesheet", styleSheet);

        Viewer viewer = new Viewer(graph, Viewer.ThreadingModel.GRAPH_IN_ANOTHER_THREAD);
        viewer.enableAutoLayout(); 
        
        ViewPanel viewPanel = viewer.addDefaultView(false); 

        muestraGrafo.removeAll();
        muestraGrafo.setLayout(new BorderLayout());
        muestraGrafo.add(viewPanel, BorderLayout.CENTER);
        
        PanelContenedor.removeAll();
        PanelContenedor.add(VistaVerRed);
        PanelContenedor.repaint();
        PanelContenedor.revalidate();
    }//GEN-LAST:event_RedGrafoActionPerformed

    private void SinapsisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SinapsisActionPerformed
        PanelContenedor.removeAll();
        PanelContenedor.add(VistaSinapsis);
        PanelContenedor.repaint();
        PanelContenedor.revalidate();
        
        ControladorPrincipal controlador = new ControladorPrincipal();
        GrafoSinaptico grafoGlobal = ControladorPrincipal.getGrafo();
        
        if (grafoGlobal != null) {
            TextAreaSinapsis.setText(controlador.mostrarListaSinapsis());
        }
    }//GEN-LAST:event_SinapsisActionPerformed

    private void IdNeuronaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IdNeuronaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IdNeuronaActionPerformed

    private void EliminarNeuronaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarNeuronaActionPerformed
    
    String idIngresado = IdNeurona.getText().trim();
        
        if (idIngresado.isEmpty() == true) {
            JOptionPane.showMessageDialog(this, "Por favor, ingrese el ID de la neurona a eliminar.", "Campo Vacío", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        ControladorPrincipal controlador = new ControladorPrincipal();
        GrafoSinaptico grafoGlobal = ControladorPrincipal.getGrafo();
        
        if (grafoGlobal.existeNeurona(idIngresado) == false) {
            JOptionPane.showMessageDialog(this, "Error: La neurona '" + idIngresado + "' no existe en la red.", "Error de Eliminación", JOptionPane.ERROR_MESSAGE);
        } else {
            grafoGlobal.eliminarNeurona(idIngresado); 
            JOptionPane.showMessageDialog(this, "Neurona '" + idIngresado + "' y todas sus conexiones fueron eliminadas permanentemente.");
        }
        
        IdNeurona.setText("");
        
        if (grafoGlobal != null) {
            TextAreaNeurona.setText(controlador.mostrarListaNeuronas());
        }
    }//GEN-LAST:event_EliminarNeuronaActionPerformed

    private void AgregarNeuronaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgregarNeuronaActionPerformed
    
    String idIngresado = IdNeurona.getText().trim();
        
        if (idIngresado.isEmpty() == true) {
            JOptionPane.showMessageDialog(this, "Por favor, ingrese un ID válido.", "Campo Vacío", JOptionPane.WARNING_MESSAGE);
            return;
        }
        ControladorPrincipal controlador = new ControladorPrincipal();
        GrafoSinaptico grafoGlobal = ControladorPrincipal.getGrafo();
        
        if (grafoGlobal.existeNeurona(idIngresado) == true) {
            JOptionPane.showMessageDialog(this, "La neurona '" + idIngresado + "' ya existe en la red.", "Aviso", JOptionPane.WARNING_MESSAGE);
        } else {
            grafoGlobal.agregarNeurona(idIngresado);
            JOptionPane.showMessageDialog(this, "Neurona '" + idIngresado + "' agregada exitosamente.");
        }
        
        IdNeurona.setText("");
        
        if (grafoGlobal != null) {
            TextAreaNeurona.setText(controlador.mostrarListaNeuronas());
        }
    }//GEN-LAST:event_AgregarNeuronaActionPerformed

    private void AgregarSinapsisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgregarSinapsisActionPerformed
        
        String origen = IdOrigen1.getText().trim();
        String destino = IdDestino.getText().trim();
        String distanciaStr = Distancia.getText().trim();
        String quimico = Neurotransmisor1.getText().trim();
        String kStr = CoeficienteK.getText().trim();
        
        if (origen.isEmpty() == true || destino.isEmpty() == true || distanciaStr.isEmpty() == true || quimico.isEmpty() == true || kStr.isEmpty() == true) {
            JOptionPane.showMessageDialog(this, "Por favor, llene todos los campos para crear la sinapsis.", "Campos Vacíos", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        try {
            double distancia = Double.parseDouble(distanciaStr);
            double k = Double.parseDouble(kStr);
            
            if (distancia>1 || distancia <=0) {
                throw new Exception("La distancia debe ser un valor entre (0,1].");
            }
            
            if (k>1 || k <=0){
                throw new Exception("El coeficiente K debe ser un valor entre (0,1].");
            }   
            
            TablaHashNeurotransmisores tablaNeuro = ControladorPrincipal.getTablaHash();
            if (tablaNeuro.buscar(quimico) == null) { 
                throw new Exception("El neurotransmisor '" + quimico + "' no existe en el diccionario cargado.");
            }
            
            ControladorPrincipal controlador = new ControladorPrincipal();
            GrafoSinaptico grafoGlobal = ControladorPrincipal.getGrafo();
            
            if (grafoGlobal.existeNeurona(origen) == true && grafoGlobal.existeNeurona(destino) == true) {
                
                String mensaje = grafoGlobal.agregarSinapsis(origen, destino, distancia, quimico, k);
                JOptionPane.showMessageDialog(this, mensaje);
                
                IdOrigen1.setText("");
                IdDestino.setText("");
                Distancia.setText("");
                Neurotransmisor1.setText("");
                CoeficienteK.setText("");
                
                if (grafoGlobal != null) {
                    TextAreaSinapsis.setText(controlador.mostrarListaSinapsis());
                }
                
            } else {
                JOptionPane.showMessageDialog(this, "Error: La neurona de origen o la de destino no existen en la red.", "Error", JOptionPane.ERROR_MESSAGE);
            }
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), "Error de Formato", JOptionPane.ERROR_MESSAGE);
        }
           
    }//GEN-LAST:event_AgregarSinapsisActionPerformed

    private void EliminarSinapsisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarSinapsisActionPerformed
String origen = IdOrigen1.getText().trim();
        String destino = IdDestino.getText().trim();
        
        if (origen.isEmpty() == true || destino.isEmpty() == true) {
            JOptionPane.showMessageDialog(this, "Por favor, ingrese el ID Origen y el ID Destino para eliminar la conexión.", "Campos Vacíos", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        ControladorPrincipal controlador = new ControladorPrincipal();
        GrafoSinaptico grafoGlobal = ControladorPrincipal.getGrafo();
        
        if (grafoGlobal.existeNeurona(origen) == true && grafoGlobal.existeNeurona(destino) == true) {
            
        if (grafoGlobal.existeSinapsis(origen, destino) == false) {
                JOptionPane.showMessageDialog(this, "Aviso: No existe ninguna conexión directa entre '" + origen + "' y '" + destino + "'.", "No encontrada", JOptionPane.WARNING_MESSAGE);
            } else {
                grafoGlobal.eliminarSinapsis(origen, destino);
                JOptionPane.showMessageDialog(this, "Se eliminó la conexión entre '" + origen + "' y '" + destino + "'.");
            }
            
            IdOrigen1.setText("");
            IdDestino.setText("");
            
            if (grafoGlobal != null) {
                TextAreaSinapsis.setText(controlador.mostrarListaSinapsis());
            }
            
        } else {
            JOptionPane.showMessageDialog(this, "Error: La neurona de origen o la de destino no existen en la red.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_EliminarSinapsisActionPerformed

    private void IdDestinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IdDestinoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IdDestinoActionPerformed

    private void IdOrigen1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IdOrigen1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IdOrigen1ActionPerformed

    private void CoeficienteKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CoeficienteKActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CoeficienteKActionPerformed

    private void DistanciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DistanciaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DistanciaActionPerformed

    private void Neurotransmisor1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Neurotransmisor1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Neurotransmisor1ActionPerformed

    private void NeurotransmisorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NeurotransmisorActionPerformed
        PanelContenedor.removeAll();
        PanelContenedor.add(VistaNeurotransmisor);
        PanelContenedor.repaint();
        PanelContenedor.revalidate(); 
        
        ControladorPrincipal controlador = new ControladorPrincipal();
        TextAreaNeurotrans.setText(controlador.mostrarListaNeurotransmisores());
    }//GEN-LAST:event_NeurotransmisorActionPerformed

    private void IdNeuronaOrigenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IdNeuronaOrigenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IdNeuronaOrigenActionPerformed

    private void IdNeuronaDestinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IdNeuronaDestinoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IdNeuronaDestinoActionPerformed

    private void simulacionfatigaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simulacionfatigaActionPerformed
        try {
            GrafoSinaptico grafoGlobal = ControladorPrincipal.getGrafo();
            if (grafoGlobal == null || grafoGlobal.isEmpty() == true) {
                JOptionPane.showMessageDialog(this, "No hay red cargada para aplicar fatiga.", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }

            Logica.SimuladorFatiga simulador = new Logica.SimuladorFatiga();
            simulador.aplicarFatiga();
            
            double factorFijo = 1.2;
            
            double fatigaActual = Double.parseDouble(fatiga.getText().replace(",", "."));
            
            double fatigaTotal;
            if (fatigaActual == 0) {
                fatigaTotal = factorFijo;
            } else {
                fatigaTotal = fatigaActual * factorFijo;
            } 
            
            fatiga.setText(String.valueOf(fatigaTotal));
            
            JOptionPane.showMessageDialog(this, "Fatiga aplicada exitosamente. Factor acumulado: " + String.valueOf(fatigaTotal));
            
        }catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al aplicar fatiga: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_simulacionfatigaActionPerformed

    private void DijkstraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DijkstraActionPerformed
        String origen = IdNeuronaOrigen.getText().trim();
        String destino = IdNeuronaDestino.getText().trim();
        
        if (origen.isEmpty() == true || destino.isEmpty() == true) {
            JOptionPane.showMessageDialog(this, "Por favor, ingrese el Origen y Destino.", "Campos Vacíos", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        GrafoSinaptico grafoGlobal = ControladorPrincipal.getGrafo();
        
        if (grafoGlobal.existeNeurona(origen) == false || grafoGlobal.existeNeurona(destino) == false) {
            JOptionPane.showMessageDialog(this, "El origen o destino no existen en la red.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        Logica.CalculadoraDijkstra calc = new Logica.CalculadoraDijkstra();
        GrafoSinaptico ruta = calc.calcularRutaMasRapida(origen, destino);
        
        Neurona neuronaDest = grafoGlobal.buscarNeurona(destino);
        if (neuronaDest.getdPesoAcumulado() == Double.MAX_VALUE) {
            JOptionPane.showMessageDialog(this, "No existe un camino físico entre '" + origen + "' y '" + destino + "'.", "Ruta Inalcanzable", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        ControladorPrincipal controlador = new ControladorPrincipal();
        String resultadoFinal = controlador.textoResultadoDijkstra(neuronaDest.getdPesoAcumulado(), ruta);
        resultDijkstra.setText(resultadoFinal);
        
        System.setProperty("org.graphstream.ui.renderer", "org.graphstream.ui.j2dviewer.J2DGraphRenderer");
        Graph graphDijkstra = new SingleGraph("GrafoDijkstra");
        graphDijkstra.setStrict(false);
        graphDijkstra.setAutoCreate(true);
        
        Neurona actualRuta = ruta.getNeuronaInicio();
        while (actualRuta != null) {
            String idNodo = actualRuta.getId();
            Node n = graphDijkstra.addNode(idNodo);
            n.setAttribute("ui.label", idNodo);
            
            if (actualRuta.getSiguiente() != null) {
                String idDestArista = actualRuta.getId();
                String idOrigArista = actualRuta.getSiguiente().getId();
                String idArista = idOrigArista + "-" + idDestArista;
                graphDijkstra.addEdge(idArista, idOrigArista, idDestArista, true);
            }
            actualRuta = actualRuta.getSiguiente();
        }
        
        graphDijkstra.setAttribute("ui.stylesheet", "node { fill-color: red; size: 30px; text-size: 20px; text-style: bold; text-alignment: center; } edge { fill-color: red; size: 3px; }");
        
        Viewer viewerDijk = new Viewer(graphDijkstra, Viewer.ThreadingModel.GRAPH_IN_ANOTHER_THREAD);
        viewerDijk.enableAutoLayout(); 
        ViewPanel viewPanelDijk = viewerDijk.addDefaultView(false); 

        grafodijkstra.removeAll();
        grafodijkstra.setLayout(new BorderLayout());
        grafodijkstra.add(viewPanelDijk, BorderLayout.CENTER);
        grafodijkstra.repaint();
        grafodijkstra.revalidate();
    }//GEN-LAST:event_DijkstraActionPerformed

    private void IdNeuronaFuenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IdNeuronaFuenteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IdNeuronaFuenteActionPerformed

    private void DFSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DFSActionPerformed
        
        String fuente = IdNeuronaFuente.getText().trim();
        
        if (fuente.isEmpty() == true) {
            JOptionPane.showMessageDialog(this, "Ingrese el ID de la Neurona Fuente.", "Campo Vacío", JOptionPane.WARNING_MESSAGE);
            return;
        }

        GrafoSinaptico grafoGlobal = ControladorPrincipal.getGrafo();
        if (grafoGlobal == null || grafoGlobal.existeNeurona(fuente) == false) {
            JOptionPane.showMessageDialog(this, "La neurona no existe o no hay red cargada.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        Logica.AnalizadorConectividad analizador = new Logica.AnalizadorConectividad();
        GrafoSinaptico rutaDFS = analizador.DFS(fuente);
        
        ControladorPrincipal controlador = new ControladorPrincipal();
        String recorridoTexto = controlador.textoRecorridoDFSoBFS(rutaDFS);
        String textoAisladas = analizador.obtenerZonasAisladas();
        String textoFinal = recorridoTexto + "\n\n" + textoAisladas;
        resultDFSyBFS.setText("Recorrido DFS:\n" + textoFinal);
        
        System.setProperty("org.graphstream.ui.renderer", "org.graphstream.ui.j2dviewer.J2DGraphRenderer");
        Graph graphDFS = new SingleGraph("GrafoDFS");
        graphDFS.setStrict(false);
        graphDFS.setAutoCreate(true);

        Neurona neuronaActual = grafoGlobal.getNeuronaInicio();
        while (neuronaActual != null) {
            String idString = neuronaActual.getId();
            Node n = graphDFS.addNode(idString);
            n.setAttribute("ui.label", idString);
            
            if (neuronaActual.getActivo() == true) {
                n.setAttribute("ui.class", "conectado");
            } else {
                n.setAttribute("ui.class", "aislado");
            }
            neuronaActual = neuronaActual.getSiguiente();
        }

        neuronaActual = grafoGlobal.getNeuronaInicio();
        while (neuronaActual != null) {
            Sinapsis sinapsisActual = neuronaActual.getConexiones().getPrimeraSinapsis();
            while (sinapsisActual != null) {
                String idOrigen = neuronaActual.getId();
                String idDestino = sinapsisActual.getDestino().getId();
                String idArista = idOrigen + "-" + idDestino;
                graphDFS.addEdge(idArista, idOrigen, idDestino, true);
                sinapsisActual = sinapsisActual.getSiguiente();
            }
            neuronaActual = neuronaActual.getSiguiente();
        }

        // Aplicamos la hoja de estilos con los colores
        String styleSheet = "node { size: 30px; text-size: 18px; text-style: bold; text-alignment: center; } " +
                            "node.conectado { fill-color: green; } " +
                            "node.aislado { fill-color: red; } " +
                            "edge { fill-color: black; }";
        graphDFS.setAttribute("ui.stylesheet", styleSheet);

        Viewer viewer = new Viewer(graphDFS, Viewer.ThreadingModel.GRAPH_IN_ANOTHER_THREAD);
        viewer.enableAutoLayout(); 
        ViewPanel viewPanel = viewer.addDefaultView(false); 

        grafo.removeAll();
        grafo.setLayout(new BorderLayout());
        grafo.add(viewPanel, BorderLayout.CENTER);
        grafo.repaint();
        grafo.revalidate();
    }//GEN-LAST:event_DFSActionPerformed

    private void BFSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BFSActionPerformed
        
        String fuente = IdNeuronaFuente.getText().trim();
        
        if (fuente.isEmpty() == true) {
            JOptionPane.showMessageDialog(this, "Ingrese el ID de la Neurona Fuente.", "Campo Vacío", JOptionPane.WARNING_MESSAGE);
            return;
        }

        GrafoSinaptico grafoGlobal = ControladorPrincipal.getGrafo();
        if (grafoGlobal == null || grafoGlobal.existeNeurona(fuente) == false) {
            JOptionPane.showMessageDialog(this, "La neurona no existe o no hay red cargada.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        Logica.AnalizadorConectividad analizador = new Logica.AnalizadorConectividad();
        GrafoSinaptico rutaBFS = analizador.BFS(fuente);
        
        ControladorPrincipal controlador = new ControladorPrincipal();
        String recorridoTexto = controlador.textoRecorridoDFSoBFS(rutaBFS);
        String textoAisladas = analizador.obtenerZonasAisladas();
        String textoFinal = recorridoTexto + "\n\n" + textoAisladas;
        resultDFSyBFS.setText("Recorrido BFS:\n" + textoFinal);
        
        System.setProperty("org.graphstream.ui.renderer", "org.graphstream.ui.j2dviewer.J2DGraphRenderer");
        Graph graphBFS = new SingleGraph("GrafoBFS");
        graphBFS.setStrict(false);
        graphBFS.setAutoCreate(true);

        Neurona neuronaActual = grafoGlobal.getNeuronaInicio();
        while (neuronaActual != null) {
            String idString = neuronaActual.getId();
            Node n = graphBFS.addNode(idString);
            n.setAttribute("ui.label", idString);
            
            if (neuronaActual.getActivo() == true) {
                n.setAttribute("ui.class", "conectado");
            } else {
                n.setAttribute("ui.class", "aislado");
            }
            neuronaActual = neuronaActual.getSiguiente();
        }

        neuronaActual = grafoGlobal.getNeuronaInicio();
        while (neuronaActual != null) {
            Sinapsis sinapsisActual = neuronaActual.getConexiones().getPrimeraSinapsis();
            while (sinapsisActual != null) {
                String idOrigen = neuronaActual.getId();
                String idDestino = sinapsisActual.getDestino().getId();
                String idArista = idOrigen + "-" + idDestino;
                graphBFS.addEdge(idArista, idOrigen, idDestino, true);
                sinapsisActual = sinapsisActual.getSiguiente();
            }
            neuronaActual = neuronaActual.getSiguiente();
        }

        String styleSheet = "node { size: 30px; text-size: 18px; text-style: bold; text-alignment: center; } " +
                            "node.conectado { fill-color: green; } " +
                            "node.aislado { fill-color: red; } " +
                            "edge { fill-color: black; }";
        graphBFS.setAttribute("ui.stylesheet", styleSheet);

        Viewer viewer = new Viewer(graphBFS, Viewer.ThreadingModel.GRAPH_IN_ANOTHER_THREAD);
        viewer.enableAutoLayout(); 
        ViewPanel viewPanel = viewer.addDefaultView(false); 

        grafo.removeAll();
        grafo.setLayout(new BorderLayout());
        grafo.add(viewPanel, BorderLayout.CENTER);
        grafo.repaint();
        grafo.revalidate();
    }//GEN-LAST:event_BFSActionPerformed

    private void dfsybfsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dfsybfsActionPerformed
        PanelContenedor.removeAll();
        PanelContenedor.add(VistaDFSyBFS);
        PanelContenedor.repaint();
        PanelContenedor.revalidate();
        
        GrafoSinaptico grafoGlobal = ControladorPrincipal.getGrafo();

        if (grafoGlobal == null || grafoGlobal.isEmpty() == true) {
            JOptionPane.showMessageDialog(this, "La red neuronal está vacía. Cargue datos primero.", "Aviso", JOptionPane.WARNING_MESSAGE);
            return;
        }

        System.setProperty("org.graphstream.ui.renderer", "org.graphstream.ui.j2dviewer.J2DGraphRenderer");
        Graph graphInicial = new SingleGraph("GrafoInicial");
        graphInicial.setStrict(false);
        graphInicial.setAutoCreate(true);

        Neurona neuronaActual = grafoGlobal.getNeuronaInicio();
        while (neuronaActual != null) {
            String idString = neuronaActual.getId();
            Node n = graphInicial.addNode(idString);
            n.setAttribute("ui.label", idString);
            neuronaActual = neuronaActual.getSiguiente();
        }

        neuronaActual = grafoGlobal.getNeuronaInicio();
        while (neuronaActual != null) {
            Sinapsis sinapsisActual = neuronaActual.getConexiones().getPrimeraSinapsis();
            while (sinapsisActual != null) {
                String idOrigen = neuronaActual.getId();
                String idDestino = sinapsisActual.getDestino().getId();
                String idArista = idOrigen + "-" + idDestino;
                graphInicial.addEdge(idArista, idOrigen, idDestino, true);
                sinapsisActual = sinapsisActual.getSiguiente();
            }
            neuronaActual = neuronaActual.getSiguiente();
        }

        String styleSheet = "node { fill-color: green; size: 30px; text-size: 18px; text-style: bold; text-alignment: center; } " +
                            "edge { fill-color: black; }";
        graphInicial.setAttribute("ui.stylesheet", styleSheet);

        Viewer viewer = new Viewer(graphInicial, Viewer.ThreadingModel.GRAPH_IN_ANOTHER_THREAD);
        viewer.enableAutoLayout(); 
        ViewPanel viewPanel = viewer.addDefaultView(false); 

        grafo.removeAll();
        grafo.setLayout(new BorderLayout());
        grafo.add(viewPanel, BorderLayout.CENTER);
        grafo.repaint();
        grafo.revalidate();
    }//GEN-LAST:event_dfsybfsActionPerformed

    private void AgregarNeurotransActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgregarNeurotransActionPerformed
        String id = IdNeurotrans.getText().trim();
        String nombre = nombreneurotrans.getText().trim();
        String efecto = efectoneurotrans.getText().trim();
        String velStr = velocidadneurotrans.getText().trim();
        String desc = descripcionneurotrans.getText().trim();

        if (id.isEmpty() || nombre.isEmpty() || efecto.isEmpty() || velStr.isEmpty() || desc.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Por favor, llene todos los campos para agregar un neurotransmisor.", "Campos Vacíos", JOptionPane.WARNING_MESSAGE);
            return;
        }

        try {
            velStr = velStr.replace(",", ".");
            double velocidad = Double.parseDouble(velStr);

            if (velocidad <= 0) {
                throw new Exception("La velocidad debe ser un número mayor a 0.");
            }

            TablaHashNeurotransmisores tablaNeuro = ControladorPrincipal.getTablaHash();

            if (tablaNeuro == null) {
                JOptionPane.showMessageDialog(this, "El diccionario no ha sido inicializado. Por favor, cargue un archivo CSV primero.", "Tabla no encontrada", JOptionPane.ERROR_MESSAGE);
                return;
            }

            if (tablaNeuro.buscar(id) != null) {
                JOptionPane.showMessageDialog(this, "El neurotransmisor con ID '" + id + "' ya existe en el diccionario.", "ID Duplicado", JOptionPane.ERROR_MESSAGE);
            } else {
                Entidades.Neurotransmisor nuevo = new Entidades.Neurotransmisor(id, nombre, efecto, velocidad, desc);
                tablaNeuro.insertar(nuevo);
                
                JOptionPane.showMessageDialog(this, "Neurotransmisor '" + nombre + "' agregado exitosamente.");
                
                IdNeurotrans.setText("");
                nombreneurotrans.setText("");
                efectoneurotrans.setText("");
                velocidadneurotrans.setText("");
                descripcionneurotrans.setText("");
            }

            ControladorPrincipal controlador = new ControladorPrincipal();
            TextAreaNeurotrans.setText(controlador.mostrarListaNeurotransmisores());
            
            VistaNeurotransmisor.repaint();
            VistaNeurotransmisor.revalidate();

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, e, "Error de Valor", JOptionPane.ERROR_MESSAGE);
    }

    }//GEN-LAST:event_AgregarNeurotransActionPerformed

    private void EliminarNeurotansActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarNeurotansActionPerformed
        String id = IdNeurotrans.getText().trim();

        if (id.isEmpty() == true) {
            JOptionPane.showMessageDialog(this, "Por favor, ingrese el ID del neurotransmisor que desea eliminar.", "Campo Vacío", JOptionPane.WARNING_MESSAGE);
            return;
        }

        TablaHashNeurotransmisores tablaNeuro = ControladorPrincipal.getTablaHash();

        if (tablaNeuro.buscar(id) == null) {
            JOptionPane.showMessageDialog(this, "No se encontró un neurotransmisor con el ID '" + id, "Error", JOptionPane.ERROR_MESSAGE);
        } else {
            tablaNeuro.eliminar(id);
            JOptionPane.showMessageDialog(this, "Neurotransmisor eliminado correctamente.");
            IdNeurotrans.setText("");
        }

        ControladorPrincipal controlador = new ControladorPrincipal();
        TextAreaNeurotrans.setText(controlador.mostrarListaNeurotransmisores());
    }//GEN-LAST:event_EliminarNeurotansActionPerformed

    private void nombreneurotransActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreneurotransActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombreneurotransActionPerformed

    private void IdNeurotransActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IdNeurotransActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IdNeurotransActionPerformed

    private void descripcionneurotransActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_descripcionneurotransActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_descripcionneurotransActionPerformed

    private void efectoneurotransActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_efectoneurotransActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_efectoneurotransActionPerformed

    private void velocidadneurotransActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_velocidadneurotransActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_velocidadneurotransActionPerformed

    private void csvneuromodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_csvneuromodActionPerformed

        if (ControladorPrincipal.getDiccionarioCargadoEnMemoria() == false) {
            JOptionPane.showMessageDialog(this, "No hay ningún diccionario cargado para guardar.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        JFileChooser fileChooser = new JFileChooser();
        FileNameExtensionFilter filter = new FileNameExtensionFilter(".CSV","csv");
        fileChooser.setFileFilter(filter);
        fileChooser.setDialogTitle("Guardar/Sobreescribir Diccionario CSV");
        
        int seleccion = fileChooser.showSaveDialog(this);
        
        if (seleccion == JFileChooser.APPROVE_OPTION) {
            File archivo = fileChooser.getSelectedFile();
            String ruta = archivo.getAbsolutePath();
            
            if (ruta.toLowerCase().endsWith(".csv") == false) {
                ruta = ruta + ".csv";
            }
            
            try {
                PrintWriter pw = new PrintWriter(new File(ruta));
                
                pw.println("id,nombre,efecto,velocidad,descripcion");

                EDD.TablaHashNeurotransmisores diccionario = ControladorPrincipal.getTablaHash();
                for (int i = 0; i < diccionario.getCapacidad(); i++) {
                    EDD.NodoHash actual = diccionario.getTabla()[i];
                    
                    while (actual != null) {
                        Entidades.Neurotransmisor n = actual.getQuimico();
                        pw.println(n.getId() + "," + n.getNombre() + "," + n.getEfecto() + "," + n.getVelocidad() + "," + n.getDescripcion());
                        actual = actual.getSiguiente();
                    }
                }
                
                pw.close();
                JOptionPane.showMessageDialog(this, "Diccionario CSV guardado/sobreescrito exitosamente.");
                
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Ocurrió un error al intentar guardar el archivo.", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_csvneuromodActionPerformed

    private void csvredmodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_csvredmodActionPerformed
        if (ControladorPrincipal.getRedCargadaEnMemoria() == false) {
            JOptionPane.showMessageDialog(this, "No hay ninguna red neuronal cargada para guardar.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        JFileChooser fileChooser = new JFileChooser();
        FileNameExtensionFilter filter = new FileNameExtensionFilter(".CSV","csv");
        fileChooser.setFileFilter(filter);
        fileChooser.setDialogTitle("Guardar/Sobreescribir Red Neuronal CSV");
        
        int seleccion = fileChooser.showSaveDialog(this);
        
        if (seleccion == JFileChooser.APPROVE_OPTION) {
            File archivo = fileChooser.getSelectedFile();
            String ruta = archivo.getAbsolutePath();
            
            if (ruta.toLowerCase().endsWith(".csv") == false) {
                ruta = ruta + ".csv";
            }
            
            try {
                PrintWriter pw = new PrintWriter(new File(ruta));
                
                // Escribimos la cabecera obligatoria
                pw.println("origen,destino,distancia,id_neurotransmisor,k");

                // Recorremos el grafo directamente
                EDD.GrafoSinaptico grafo = ControladorPrincipal.getGrafo();
                Entidades.Neurona actual = grafo.getNeuronaInicio();
                
                while (actual != null) {
                    Entidades.Sinapsis sinapsisActual = actual.getConexiones().getPrimeraSinapsis();
                    
                    while (sinapsisActual != null) {
                        pw.println(actual.getId() + "," + sinapsisActual.getDestino().getId() + "," + sinapsisActual.getDistancia() + "," + sinapsisActual.getIdNeurotransmisor() + "," + sinapsisActual.getK());
                        sinapsisActual = sinapsisActual.getSiguiente();
                    }
                    
                    actual = actual.getSiguiente();
                }
                
                pw.close();
                JOptionPane.showMessageDialog(this, "Red Neuronal CSV guardada/sobreescrita exitosamente.");
                
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Ocurrió un error al intentar guardar el archivo.", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    
    }//GEN-LAST:event_csvredmodActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new InterfazUsuario().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AgregarNeurona;
    private javax.swing.JButton AgregarNeurotrans;
    private javax.swing.JButton AgregarSinapsis;
    private javax.swing.JTextArea AreaTextoNeuro;
    private javax.swing.JTextArea AreaTextoRed;
    private javax.swing.JButton BFS;
    private javax.swing.JButton BotonDatosRed;
    private javax.swing.JButton BotonDicNeuro;
    private javax.swing.JButton CargaCSV;
    private javax.swing.JTextField CoeficienteK;
    private javax.swing.JButton DFS;
    private javax.swing.JButton Dijkstra;
    private javax.swing.JTextField Distancia;
    private javax.swing.JButton EliminarNeurona;
    private javax.swing.JButton EliminarNeurotans;
    private javax.swing.JButton EliminarSinapsis;
    private javax.swing.JTextField IdDestino;
    private javax.swing.JTextField IdNeurona;
    private javax.swing.JTextField IdNeuronaDestino;
    private javax.swing.JTextField IdNeuronaFuente;
    private javax.swing.JTextField IdNeuronaOrigen;
    private javax.swing.JTextField IdNeurotrans;
    private javax.swing.JTextField IdOrigen1;
    private javax.swing.JScrollPane NeuronaScroll;
    private javax.swing.JButton Neuronas;
    private javax.swing.JButton Neurotransmisor;
    private javax.swing.JTextField Neurotransmisor1;
    private javax.swing.JPanel PanelContenedor;
    private javax.swing.JButton RedGrafo;
    private javax.swing.JScrollPane SalidaCSVdicNeuro;
    private javax.swing.JScrollPane SalidaCSVred;
    private javax.swing.JPanel Sidebar;
    private javax.swing.JButton SimulacionDijkstra;
    private javax.swing.JButton Sinapsis;
    private javax.swing.JTextArea TextAreaNeurona;
    private javax.swing.JTextArea TextAreaNeurotrans;
    private javax.swing.JTextArea TextAreaSinapsis;
    private javax.swing.JPanel VistaCargaCSV;
    private javax.swing.JPanel VistaDFSyBFS;
    private javax.swing.JPanel VistaDijkstra;
    private javax.swing.JPanel VistaInicio;
    private javax.swing.JPanel VistaNeurona;
    private javax.swing.JPanel VistaNeurotransmisor;
    private javax.swing.JPanel VistaSinapsis;
    private javax.swing.JPanel VistaVerRed;
    private javax.swing.JButton csvneuromod;
    private javax.swing.JButton csvredmod;
    private javax.swing.JTextField descripcionneurotrans;
    private javax.swing.JButton dfsybfs;
    private javax.swing.JTextField efectoneurotrans;
    private javax.swing.JTextField fatiga;
    private javax.swing.JPanel grafo;
    private javax.swing.JPanel grafodijkstra;
    private javax.swing.JPanel grafooriginal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JPanel muestraGrafo;
    private javax.swing.JTextField nombreneurotrans;
    private javax.swing.JTextArea resultDFSyBFS;
    private javax.swing.JTextArea resultDijkstra;
    private javax.swing.JButton simulacionfatiga;
    private javax.swing.JTextField velocidadneurotrans;
    // End of variables declaration//GEN-END:variables
}