/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaz;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import java.io.File;
import java.io.BufferedReader;
import java.io.FileReader;
import EDD.GrafoSinaptico;
import EDD.TablaHashNeurotransmisores;
import Entidades.Neurona;
import Entidades.Sinapsis;
import Logica.ControladorPrincipal;
import java.awt.BorderLayout;
import javax.swing.JOptionPane;

import org.graphstream.graph.Graph;
import org.graphstream.graph.Node;
import org.graphstream.graph.Edge;
import org.graphstream.graph.implementations.SingleGraph;
import org.graphstream.ui.view.Viewer;
import org.graphstream.ui.swingViewer.ViewPanel;

/**
 *
 * @author gonzalo
 */
public class InterfazUsuario extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(InterfazUsuario.class.getName());

    /**
     * Creates new form Interfaz
     */
    public InterfazUsuario() {
    
        initComponents();
        PanelContenedor.removeAll();
        PanelContenedor.add(VistaInicio); 
        PanelContenedor.repaint();
        PanelContenedor.revalidate();
        
        this.setLocationRelativeTo(null); 
        this.setResizable(false); 
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Sidebar = new javax.swing.JPanel();
        CargaCSV = new javax.swing.JButton();
        Neuronas = new javax.swing.JButton();
        Sinapsis = new javax.swing.JButton();
        RedGrafo = new javax.swing.JButton();
        SimulacionDijkstra = new javax.swing.JButton();
        dfsybfs = new javax.swing.JButton();
        Neurotransmisor = new javax.swing.JButton();
        PanelContenedor = new javax.swing.JPanel();
        VistaCargaCSV = new javax.swing.JPanel();
        BotonDatosRed = new javax.swing.JButton();
        BotonDicNeuro = new javax.swing.JButton();
        SalidaCSVdicNeuro = new javax.swing.JScrollPane();
        AreaTextoNeuro = new javax.swing.JTextArea();
        SalidaCSVred = new javax.swing.JScrollPane();
        AreaTextoRed = new javax.swing.JTextArea();
        VistaNeurona = new javax.swing.JPanel();
        NeuronaScroll = new javax.swing.JScrollPane();
        TextAreaNeurona = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        IdNeurona = new javax.swing.JTextField();
        EliminarNeurona = new javax.swing.JButton();
        AgregarNeurona = new javax.swing.JButton();
        VistaSinapsis = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        AgregarSinapsis = new javax.swing.JButton();
        EliminarSinapsis = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TextAreaSinapsis = new javax.swing.JTextArea();
        IdDestino = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        IdOrigen1 = new javax.swing.JTextField();
        CoeficienteK = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        Distancia = new javax.swing.JTextField();
        Neurotransmisor1 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        VistaVerRed = new javax.swing.JPanel();
        muestraGrafo = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        VistaDijkstra = new javax.swing.JPanel();
        VistaDFSyBFS = new javax.swing.JPanel();
        VistaInicio = new javax.swing.JPanel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Sidebar.setBackground(new java.awt.Color(51, 51, 51));
        Sidebar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        CargaCSV.setText("Carga CSV");
        CargaCSV.addActionListener(this::CargaCSVActionPerformed);
        Sidebar.add(CargaCSV, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 39, 167, -1));

        Neuronas.setText("Edición Neurona");
        Neuronas.addActionListener(this::NeuronasActionPerformed);
        Sidebar.add(Neuronas, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 114, 167, -1));

        Sinapsis.setText("Edición Sinapsis");
        Sinapsis.addActionListener(this::SinapsisActionPerformed);
        Sidebar.add(Sinapsis, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 170, -1));

        RedGrafo.setText("Ver Red Neuronal");
        RedGrafo.addActionListener(this::RedGrafoActionPerformed);
        Sidebar.add(RedGrafo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, 167, -1));

        SimulacionDijkstra.setText("Simulación Dijkstra");
        SimulacionDijkstra.addActionListener(this::SimulacionDijkstraActionPerformed);
        Sidebar.add(SimulacionDijkstra, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, 167, -1));

        dfsybfs.setText("Simulación DFS y BFS");
        Sidebar.add(dfsybfs, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 420, 167, -1));

        Neurotransmisor.setText("Edición Neurotrans.");
        Neurotransmisor.addActionListener(this::NeurotransmisorActionPerformed);
        Sidebar.add(Neurotransmisor, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 170, -1));

        getContentPane().add(Sidebar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 210, 510));

        PanelContenedor.setLayout(new java.awt.CardLayout());

        VistaCargaCSV.setBackground(new java.awt.Color(245, 245, 245));
        VistaCargaCSV.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BotonDatosRed.setBackground(new java.awt.Color(245, 245, 245));
        BotonDatosRed.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        BotonDatosRed.setText("Cargar CSV red sináptica");
        BotonDatosRed.addActionListener(this::BotonDatosRedActionPerformed);
        VistaCargaCSV.add(BotonDatosRed, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 40, 360, -1));

        BotonDicNeuro.setBackground(new java.awt.Color(245, 245, 245));
        BotonDicNeuro.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        BotonDicNeuro.setText("Cargar CSV diccionario de neurotransmisores");
        BotonDicNeuro.addActionListener(this::BotonDicNeuroActionPerformed);
        VistaCargaCSV.add(BotonDicNeuro, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 270, 350, -1));

        AreaTextoNeuro.setEditable(false);
        AreaTextoNeuro.setColumns(20);
        AreaTextoNeuro.setRows(5);
        SalidaCSVdicNeuro.setViewportView(AreaTextoNeuro);

        VistaCargaCSV.add(SalidaCSVdicNeuro, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 310, 560, 170));

        AreaTextoRed.setEditable(false);
        AreaTextoRed.setColumns(20);
        AreaTextoRed.setRows(5);
        SalidaCSVred.setViewportView(AreaTextoRed);

        VistaCargaCSV.add(SalidaCSVred, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, 560, 170));

        PanelContenedor.add(VistaCargaCSV, "card7");

        VistaNeurona.setBackground(new java.awt.Color(245, 245, 245));
        VistaNeurona.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TextAreaNeurona.setColumns(20);
        TextAreaNeurona.setRows(5);
        NeuronaScroll.setViewportView(TextAreaNeurona);

        VistaNeurona.add(NeuronaScroll, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, 560, 280));

        jLabel4.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        jLabel4.setText("Insete el ID de la Neurona que desea Agregar o Eliminar");
        VistaNeurona.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, -1, -1));

        IdNeurona.addActionListener(this::IdNeuronaActionPerformed);
        VistaNeurona.add(IdNeurona, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, 360, 40));

        EliminarNeurona.setText("Eliminar Neurona");
        EliminarNeurona.addActionListener(this::EliminarNeuronaActionPerformed);
        VistaNeurona.add(EliminarNeurona, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, 150, 40));

        AgregarNeurona.setText("Agregar Neurona");
        AgregarNeurona.addActionListener(this::AgregarNeuronaActionPerformed);
        VistaNeurona.add(AgregarNeurona, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 120, 150, 40));

        PanelContenedor.add(VistaNeurona, "card6");

        VistaSinapsis.setBackground(new java.awt.Color(245, 245, 245));
        VistaSinapsis.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        jLabel6.setText("ID Destino");
        VistaSinapsis.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, -1, -1));

        AgregarSinapsis.setText("Agregar Sinapsis");
        AgregarSinapsis.addActionListener(this::AgregarSinapsisActionPerformed);
        VistaSinapsis.add(AgregarSinapsis, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 220, 150, 40));

        EliminarSinapsis.setText("Eliminar Sinapsis");
        EliminarSinapsis.addActionListener(this::EliminarSinapsisActionPerformed);
        VistaSinapsis.add(EliminarSinapsis, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 220, 150, 40));

        TextAreaSinapsis.setColumns(20);
        TextAreaSinapsis.setRows(5);
        jScrollPane1.setViewportView(TextAreaSinapsis);

        VistaSinapsis.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, 580, 200));

        IdDestino.addActionListener(this::IdDestinoActionPerformed);
        VistaSinapsis.add(IdDestino, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 130, 160, 30));

        jLabel7.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        jLabel7.setText("Obligatorio para Agregar no para Eliminar");
        VistaSinapsis.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 30, -1, -1));

        jLabel8.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        jLabel8.setText("ID Origen");
        VistaSinapsis.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, -1, -1));

        IdOrigen1.addActionListener(this::IdOrigen1ActionPerformed);
        VistaSinapsis.add(IdOrigen1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 90, 160, 30));

        CoeficienteK.addActionListener(this::CoeficienteKActionPerformed);
        VistaSinapsis.add(CoeficienteK, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 150, 160, 30));

        jLabel9.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        jLabel9.setText("Coef. K");
        VistaSinapsis.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 160, 60, -1));

        jLabel10.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        jLabel10.setText("Campos para Agregar o Eliminar Sinapsis");
        VistaSinapsis.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, -1, -1));

        jLabel11.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        jLabel11.setText("Distancia");
        VistaSinapsis.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 80, -1, -1));

        Distancia.addActionListener(this::DistanciaActionPerformed);
        VistaSinapsis.add(Distancia, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 70, 160, 30));

        Neurotransmisor1.addActionListener(this::Neurotransmisor1ActionPerformed);
        VistaSinapsis.add(Neurotransmisor1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 110, 160, 30));

        jLabel12.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        jLabel12.setText("ID Neurotr.");
        VistaSinapsis.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 120, 80, -1));

        PanelContenedor.add(VistaSinapsis, "card3");

        VistaVerRed.setBackground(new java.awt.Color(245, 245, 245));
        VistaVerRed.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        VistaVerRed.add(muestraGrafo, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, 540, 390));

        jLabel5.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        jLabel5.setText("Grafo Sináptico Resultante");
        VistaVerRed.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 30, 340, 30));

        PanelContenedor.add(VistaVerRed, "card2");

        VistaDijkstra.setBackground(new java.awt.Color(245, 245, 245));
        VistaDijkstra.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        PanelContenedor.add(VistaDijkstra, "card4");

        VistaDFSyBFS.setBackground(new java.awt.Color(245, 245, 245));
        VistaDFSyBFS.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        PanelContenedor.add(VistaDFSyBFS, "card5");

        VistaInicio.setBackground(new java.awt.Color(245, 245, 245));
        VistaInicio.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel26.setBackground(new java.awt.Color(0, 0, 0));
        jLabel26.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 1, 30)); // NOI18N
        jLabel26.setText("Bienvenido al SynapseLogic ");
        VistaInicio.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 40, 440, 60));

        jLabel27.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(51, 51, 51));
        jLabel27.setText("Grupo 1H");
        VistaInicio.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 340, -1, -1));

        jLabel28.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(51, 51, 51));
        jLabel28.setText("Presiona el botón de la acción que deseas realizar");
        VistaInicio.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 110, -1, -1));

        jLabel1.setText("Gonzalo Maza CI 32.710.984");
        VistaInicio.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 380, -1, -1));

        jLabel2.setText("Santiago Hernàndez CI 31.539.266");
        VistaInicio.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 440, -1, -1));

        jLabel3.setText("Andrés Benezra CI 30.715.072");
        VistaInicio.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 410, -1, -1));

        PanelContenedor.add(VistaInicio, "card8");

        getContentPane().add(PanelContenedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 0, 640, 510));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CargaCSVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CargaCSVActionPerformed
        PanelContenedor.removeAll();
        PanelContenedor.add(VistaCargaCSV);
        PanelContenedor.repaint();
        PanelContenedor.revalidate();    
    }//GEN-LAST:event_CargaCSVActionPerformed

    private void NeuronasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NeuronasActionPerformed
        PanelContenedor.removeAll();
        PanelContenedor.add(VistaNeurona);
        PanelContenedor.repaint();
        PanelContenedor.revalidate(); 
        
        ControladorPrincipal controlador = new ControladorPrincipal();
        GrafoSinaptico grafoGlobal = ControladorPrincipal.getGrafo();
        
        if (grafoGlobal != null) {
            TextAreaNeurona.setText(controlador.mostrarListaNeuronas());
        }   
      }//GEN-LAST:event_NeuronasActionPerformed

    private void SimulacionDijkstraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SimulacionDijkstraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SimulacionDijkstraActionPerformed

    private void BotonDatosRedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonDatosRedActionPerformed

        boolean redCargadaEnMemoria = ControladorPrincipal.getRedCargadaEnMemoria();

        if (redCargadaEnMemoria) {
            JOptionPane.showMessageDialog(this, 
                "Alerta: Ya hay una red  cargada en memoria.\nRecuerda guardar tus datos actuales si hiciste modificaciones.", 
                "Advertencia de Sobreescritura", 
                JOptionPane.WARNING_MESSAGE);
        }

        JFileChooser fileChooser = new JFileChooser();
        FileNameExtensionFilter filter = new FileNameExtensionFilter(".CSV","csv");
        fileChooser.setFileSelectionMode(JFileChooser.FILES_ONLY);
        fileChooser.setFileFilter(filter);
        fileChooser.setDialogTitle("Seleccione el archivo CSV de la Red Neuronal");
        
        int seleccion = fileChooser.showOpenDialog(this);
        
        if (seleccion == JFileChooser.APPROVE_OPTION) {

            File archivo = fileChooser.getSelectedFile();
            String ruta = archivo.getAbsolutePath(); 
            
            try {
                BufferedReader lector = new BufferedReader(new FileReader(archivo));
                String linea;
                
                
                Logica.LectorCSV lectorLogico = new Logica.LectorCSV();
                Boolean aprobado = lectorLogico.leerRedNeuronal(ruta);
               
                if (aprobado == true) {
                    String contenidoCompleto = ""; 
                    
                    while ((linea = lector.readLine()) != null) {
                        contenidoCompleto += linea + "\n";
                    }
                    lector.close();
                    
                    AreaTextoRed.setText(contenidoCompleto);

                
                    ControladorPrincipal.setRedCargadaEnMemoria(true);
                }
                
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, "Error al leer el archivo: " + ex.getMessage());
            }
        }
    }//GEN-LAST:event_BotonDatosRedActionPerformed

    private void BotonDicNeuroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonDicNeuroActionPerformed
        
        boolean diccionario = ControladorPrincipal.getDiccionarioCargadoEnMemoria();


        if (diccionario == true) {
            JOptionPane.showMessageDialog(this, 
                "Alerta: Ya hay un diccionario de neurotransmisores cargado en memoria.\nRecuerda guardar tus datos actuales si hiciste modificaciones.", 
                "Advertencia de Sobreescritura", 
                JOptionPane.WARNING_MESSAGE);
        }

        JFileChooser fileChooser = new JFileChooser();
        FileNameExtensionFilter filter = new FileNameExtensionFilter(".CSV","csv");
        fileChooser.setFileSelectionMode(JFileChooser.FILES_ONLY);
        fileChooser.setFileFilter(filter);
        fileChooser.setDialogTitle("Seleccione el archivo CSV del Diccionario de Neurotransmisores");
        
        int seleccion = fileChooser.showOpenDialog(this);
        
        if (seleccion == JFileChooser.APPROVE_OPTION) {

            File archivo = fileChooser.getSelectedFile();
            String ruta = archivo.getAbsolutePath(); 
            
            try {
                BufferedReader lector = new BufferedReader(new FileReader(archivo));
                String linea;
                
                
                Logica.LectorCSV lectorLogico = new Logica.LectorCSV();
                Boolean aprobado = lectorLogico.leerDiccionarioHash(ruta);
                
                if (aprobado == true) {
                    String contenidoCompleto = ""; 
                    
                    while ((linea = lector.readLine()) != null) {
                        contenidoCompleto += linea + "\n";
                    }
                    lector.close();
                    
                    AreaTextoNeuro.setText(contenidoCompleto);
                    
                    ControladorPrincipal.setDiccionarioCargadoEnMemoria(true);
                }
                
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, "Error al leer el archivo: " + ex.getMessage());
            }
        }
    }//GEN-LAST:event_BotonDicNeuroActionPerformed

    private void RedGrafoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RedGrafoActionPerformed
        
        GrafoSinaptico grafoGlobal = ControladorPrincipal.getGrafo();

        if (grafoGlobal.isEmpty()) {
            JOptionPane.showMessageDialog(this, "La red neuronal está vacía. Cargue el CSV primero.", "Aviso", JOptionPane.WARNING_MESSAGE);
            return;
        }

        System.setProperty("org.graphstream.ui.renderer", "org.graphstream.ui.j2dviewer.J2DGraphRenderer");
        Graph graph = new SingleGraph("Cerebro");
        graph.setStrict(false);
        graph.setAutoCreate(true);

        Neurona neuronaActual = grafoGlobal.getNeuronaInicio();
        while (neuronaActual != null) {
            if (neuronaActual.getActivo()) {
                Node n = graph.addNode(neuronaActual.getId());
                n.setAttribute("ui.label", neuronaActual.getId()); 
            }
            neuronaActual = neuronaActual.getSiguiente();
        }

        neuronaActual = grafoGlobal.getNeuronaInicio();
        while (neuronaActual != null) {
                Sinapsis sinapsisActual = neuronaActual.getConexiones().getPrimeraSinapsis();
                
                while (sinapsisActual != null) {
                    if (sinapsisActual.getDestino().getActivo()) {
                        String idOrigen = neuronaActual.getId();
                        String idDestino = sinapsisActual.getDestino().getId();
                        String idArista = idOrigen + "-" + idDestino;

                        graph.addEdge(idArista, idOrigen, idDestino, true);
                    }
                    sinapsisActual = sinapsisActual.getSiguiente();
                }
            
            neuronaActual = neuronaActual.getSiguiente();
        }
        
            String styleSheet = "node {" +
                            "   fill-color: green;" +
                            "   size: 30px;" +
                            "   text-size: 24px;" +         
                            "   text-style: bold;" +        
                            "   text-alignment: center;" +
                            "}" +
                            "edge {" +
                            "   fill-color: black;" +
                            "}";
        graph.setAttribute("ui.stylesheet", styleSheet);

        Viewer viewer = new Viewer(graph, Viewer.ThreadingModel.GRAPH_IN_ANOTHER_THREAD);
        viewer.enableAutoLayout(); 
        
        ViewPanel viewPanel = viewer.addDefaultView(false); 

        muestraGrafo.removeAll();
        muestraGrafo.setLayout(new BorderLayout());
        muestraGrafo.add(viewPanel, BorderLayout.CENTER);
        
        PanelContenedor.removeAll();
        PanelContenedor.add(VistaVerRed);
        PanelContenedor.repaint();
        PanelContenedor.revalidate();
    }//GEN-LAST:event_RedGrafoActionPerformed

    private void SinapsisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SinapsisActionPerformed
        PanelContenedor.removeAll();
        PanelContenedor.add(VistaSinapsis);
        PanelContenedor.repaint();
        PanelContenedor.revalidate();
        
        ControladorPrincipal controlador = new ControladorPrincipal();
        GrafoSinaptico grafoGlobal = ControladorPrincipal.getGrafo();
        
        if (grafoGlobal != null) {
            TextAreaSinapsis.setText(controlador.mostrarListaSinapsis());
        }
    }//GEN-LAST:event_SinapsisActionPerformed

    private void IdNeuronaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IdNeuronaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IdNeuronaActionPerformed

    private void EliminarNeuronaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarNeuronaActionPerformed
    
    String idIngresado = IdNeurona.getText().trim();
        
        if (idIngresado.isEmpty() == true) {
            JOptionPane.showMessageDialog(this, "Por favor, ingrese el ID de la neurona a eliminar.", "Campo Vacío", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        ControladorPrincipal controlador = new ControladorPrincipal();
        GrafoSinaptico grafoGlobal = ControladorPrincipal.getGrafo();
        
        if (grafoGlobal.existeNeurona(idIngresado) == false) {
            JOptionPane.showMessageDialog(this, "Error: La neurona '" + idIngresado + "' no existe en la red.", "Error de Eliminación", JOptionPane.ERROR_MESSAGE);
        } else {
            grafoGlobal.eliminarNeurona(idIngresado); 
            JOptionPane.showMessageDialog(this, "Neurona '" + idIngresado + "' y todas sus conexiones fueron eliminadas permanentemente.");
        }
        
        IdNeurona.setText("");
        
        if (grafoGlobal != null) {
            TextAreaNeurona.setText(controlador.mostrarListaNeuronas());
        }
    }//GEN-LAST:event_EliminarNeuronaActionPerformed

    private void AgregarNeuronaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgregarNeuronaActionPerformed
    
    String idIngresado = IdNeurona.getText().trim();
        
        if (idIngresado.isEmpty() == true) {
            JOptionPane.showMessageDialog(this, "Por favor, ingrese un ID válido.", "Campo Vacío", JOptionPane.WARNING_MESSAGE);
            return;
        }
        ControladorPrincipal controlador = new ControladorPrincipal();
        GrafoSinaptico grafoGlobal = ControladorPrincipal.getGrafo();
        
        if (grafoGlobal.existeNeurona(idIngresado) == true) {
            JOptionPane.showMessageDialog(this, "La neurona '" + idIngresado + "' ya existe en la red.", "Aviso", JOptionPane.WARNING_MESSAGE);
        } else {
            grafoGlobal.agregarNeurona(idIngresado);
            JOptionPane.showMessageDialog(this, "Neurona '" + idIngresado + "' agregada exitosamente.");
        }
        
        IdNeurona.setText("");
        
        if (grafoGlobal != null) {
            TextAreaNeurona.setText(controlador.mostrarListaNeuronas());
        }
    }//GEN-LAST:event_AgregarNeuronaActionPerformed

    private void AgregarSinapsisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgregarSinapsisActionPerformed
        
        String origen = IdOrigen1.getText().trim();
        String destino = IdDestino.getText().trim();
        String distanciaStr = Distancia.getText().trim();
        String quimico = Neurotransmisor1.getText().trim();
        String kStr = CoeficienteK.getText().trim();
        
        if (origen.isEmpty() == true || destino.isEmpty() == true || distanciaStr.isEmpty() == true || quimico.isEmpty() == true || kStr.isEmpty() == true) {
            JOptionPane.showMessageDialog(this, "Por favor, llene todos los campos para crear la sinapsis.", "Campos Vacíos", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        try {
            double distancia = Double.parseDouble(distanciaStr);
            double k = Double.parseDouble(kStr);
            
            if (distancia>1 || distancia <0) {
                throw new Exception("La distancia debe ser un valor entre 0 y 1.");
            }
            
            if (k>1 || k <0){
                throw new Exception("El coeficiente K debe ser un valor entre 0 y 1.");
            }   
            
            TablaHashNeurotransmisores tablaNeuro = ControladorPrincipal.getTablaHash();
            if (tablaNeuro.buscar(quimico) == null) { 
                throw new Exception("El neurotransmisor '" + quimico + "' no existe en el diccionario cargado.");
            }
            
            ControladorPrincipal controlador = new ControladorPrincipal();
            GrafoSinaptico grafoGlobal = ControladorPrincipal.getGrafo();
            
            if (grafoGlobal.existeNeurona(origen) == true && grafoGlobal.existeNeurona(destino) == true) {
                
                String mensaje = grafoGlobal.agregarSinapsis(origen, destino, distancia, quimico, k);
                JOptionPane.showMessageDialog(this, mensaje);
                
                IdOrigen1.setText("");
                IdDestino.setText("");
                Distancia.setText("");
                Neurotransmisor1.setText("");
                CoeficienteK.setText("");
                
                if (grafoGlobal != null) {
                    TextAreaSinapsis.setText(controlador.mostrarListaSinapsis());
                }
                
            } else {
                JOptionPane.showMessageDialog(this, "Error: La neurona de origen o la de destino no existen en la red.", "Error", JOptionPane.ERROR_MESSAGE);
            }
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), "Error de Formato", JOptionPane.ERROR_MESSAGE);
        }
           
    }//GEN-LAST:event_AgregarSinapsisActionPerformed

    private void EliminarSinapsisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarSinapsisActionPerformed
String origen = IdOrigen1.getText().trim();
        String destino = IdDestino.getText().trim();
        
        if (origen.isEmpty() == true || destino.isEmpty() == true) {
            JOptionPane.showMessageDialog(this, "Por favor, ingrese el ID Origen y el ID Destino para eliminar la conexión.", "Campos Vacíos", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        ControladorPrincipal controlador = new ControladorPrincipal();
        GrafoSinaptico grafoGlobal = ControladorPrincipal.getGrafo();
        
        if (grafoGlobal.existeNeurona(origen) == true && grafoGlobal.existeNeurona(destino) == true) {
            
        if (grafoGlobal.existeSinapsis(origen, destino) == false) {
                JOptionPane.showMessageDialog(this, "Aviso: No existe ninguna conexión directa entre '" + origen + "' y '" + destino + "'.", "No encontrada", JOptionPane.WARNING_MESSAGE);
            } else {
                grafoGlobal.eliminarSinapsis(origen, destino);
                JOptionPane.showMessageDialog(this, "Se eliminó la conexión entre '" + origen + "' y '" + destino + "'.");
            }
            
            IdOrigen1.setText("");
            IdDestino.setText("");
            
            if (grafoGlobal != null) {
                TextAreaSinapsis.setText(controlador.mostrarListaSinapsis());
            }
            
        } else {
            JOptionPane.showMessageDialog(this, "Error: La neurona de origen o la de destino no existen en la red.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_EliminarSinapsisActionPerformed

    private void IdDestinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IdDestinoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IdDestinoActionPerformed

    private void IdOrigen1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IdOrigen1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IdOrigen1ActionPerformed

    private void CoeficienteKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CoeficienteKActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CoeficienteKActionPerformed

    private void DistanciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DistanciaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DistanciaActionPerformed

    private void Neurotransmisor1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Neurotransmisor1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Neurotransmisor1ActionPerformed

    private void NeurotransmisorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NeurotransmisorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NeurotransmisorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new InterfazUsuario().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AgregarNeurona;
    private javax.swing.JButton AgregarSinapsis;
    private javax.swing.JTextArea AreaTextoNeuro;
    private javax.swing.JTextArea AreaTextoRed;
    private javax.swing.JButton BotonDatosRed;
    private javax.swing.JButton BotonDicNeuro;
    private javax.swing.JButton CargaCSV;
    private javax.swing.JTextField CoeficienteK;
    private javax.swing.JTextField Distancia;
    private javax.swing.JButton EliminarNeurona;
    private javax.swing.JButton EliminarSinapsis;
    private javax.swing.JTextField IdDestino;
    private javax.swing.JTextField IdNeurona;
    private javax.swing.JTextField IdOrigen1;
    private javax.swing.JScrollPane NeuronaScroll;
    private javax.swing.JButton Neuronas;
    private javax.swing.JButton Neurotransmisor;
    private javax.swing.JTextField Neurotransmisor1;
    private javax.swing.JPanel PanelContenedor;
    private javax.swing.JButton RedGrafo;
    private javax.swing.JScrollPane SalidaCSVdicNeuro;
    private javax.swing.JScrollPane SalidaCSVred;
    private javax.swing.JPanel Sidebar;
    private javax.swing.JButton SimulacionDijkstra;
    private javax.swing.JButton Sinapsis;
    private javax.swing.JTextArea TextAreaNeurona;
    private javax.swing.JTextArea TextAreaSinapsis;
    private javax.swing.JPanel VistaCargaCSV;
    private javax.swing.JPanel VistaDFSyBFS;
    private javax.swing.JPanel VistaDijkstra;
    private javax.swing.JPanel VistaInicio;
    private javax.swing.JPanel VistaNeurona;
    private javax.swing.JPanel VistaSinapsis;
    private javax.swing.JPanel VistaVerRed;
    private javax.swing.JButton dfsybfs;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel muestraGrafo;
    // End of variables declaration//GEN-END:variables
}